services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jpop_app
    env_file:
      - .env.container
    depends_on:
      - db
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
    environment:
      PYTHONPATH: /workspace:/workspace/src
    command: sleep infinity

  db:
    image: postgres:15
    container_name: jpop_db
    restart: always
    env_file:
      - .env.container
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
